### ISSUE TITLE
Wifi sensor doesn't turn on with Aware

### ISSUE THREAD

**Issue by juancamilo87** [denzilferreira/aware-plugin-template#2]
If <b>WiFi</b> is <b>off</b> on the phone it doesn't turn on with Aware: 

>Aware.setSetting(context, Aware_Preferences.STATUS_WIFI, true);
Aware.setSetting(context, Aware_Preferences.FREQUENCY_WIFI, 60);
Intent applySettings = new Intent(Aware.ACTION_AWARE_REFRESH);
context.sendBroadcast(applySettings);

Even not using the template but just the Aware client. Manually turning Wifi sensor on under Sensors tab when Wifi is off doesn't turn it on. This is the LogCat:

>03-22 15:16:05.707    8094-8094/? D/AWARE﹕ Updated: status_wifi=true
03-22 15:16:05.720    8094-8094/? D/AWARE﹕ AWARE sensor created!
03-22 15:16:05.729    8094-8094/? D/AWARE﹕ AWARE sensor terminated...
03-22 15:16:05.730    8094-8094/? D/AWARE﹕ WiFi service terminated...

Workaround is turning Wifi manually using the <b>WifiManager</b>.

Device info:
Nexus 5
Android 5.0.1
Aware version 364

**Comment by denzilferreira** [comment]
Hi,


This was a design decision: if the user doesn’t want the Wi-Fi on, we don’t activate it against their will. It’s not a bug. The logging resumes if the user turns the Wi-Fi on.


A plugin developer may overrule this decision by prompting the user to activate the Wi-Fi accordingly or forcing the Wi-Fi on and off from within the plugin.


	Denzil;
