### ISSUE TITLE
Plugin database does not sync to server

### ISSUE THREAD

**Issue by tonianelope** [denzilferreira/aware-plugin-template#9]
As a project for a client we are creating a plugin for the aware framework.

The issue I have encountered is that the data from the plugin tables is not synced to the server. 
I can see the table in the database for the test study but it stays empty.
The plugin joins the test study using `Aware.joinStudy(this, studyURL)` in the onCreate() method.
The `Aware_Plugin` database fields are initialized:
`DATABASE_TABLES = Provider.DATABASE_TABLES; `
`TABLES_FIELDS = Provider.TABLES_FIELDS; `
`CONTEXT_URIS = new Uri[]{ Provider.Plugin_Survey_Data.CONTENT_URI };`
However on receiving  `Aware.ACTION_AWARE_SYNC_DATA` I get the following debug log in Android studio:
`D/AWARE: No database to backup!`
even though DATABASE_TABLES, TABLE_FIELDS and CONTEXT_URIS are initialized and not null.

Why does `Aware_Plugin ContextBroadcaster` not have the initialized database values?
@denzilferreira

**Comment by denzilferreira** [comment]
Hum... Is it possible to see the plugin code? We recently made some changes
on how we handle the permissions. See the latest plugin template and the
respective development branches as you should be developing against the
development branch.

**Comment by tonianelope** [comment]
One of the changes from the - Simplify plugins. No need to handle permissions. commit could not be adapted.
`if (PERMISSIONS_OK)` 
Since `PERMISSIONS_OK` is not declared etc. anywhere else in the code android studio can't resolve the symbol. 
I'll see what i can do about the code and revise if any other changes are missing from our plugin code.

**Comment by denzilferreira** [comment]
It is declared in the super class (Aware_Plugin). My guess is you are not using the latest library.

Make sure that on your build.gradle, you have:

repositories {
    maven { url 'https://jitpack.io' } //this allows library generation directly from GitHub source-code
}

configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, ‘seconds’

}

dependencies {
	…
	compile "com.github.denzilferreira:aware-client:development-SNAPSHOT"
}

**Comment by tonianelope** [comment]
Yeah, I still had aware-client-master-SNAPSHOT as dependency.
I updated the dependencies and the rest of the code but it still says no database to back up.
So I'm not sure if I missed something or why the Aware_Plugin code does not work.

The plugin code can be found on the database branch:
[https://github.com/sengleung/aware-plugin-survey/tree/database](url)

**Comment by tonianelope** [comment]
Syncing of the database works perfectly now thanks to the code updates.

Thanks
